### ISSUE TITLE
bug: wrong type response (1)

### ISSUE THREAD

**Issue by ruslankotliar** [YukihiroSM/web_and_coffee#34]
route: `api/user/projects`

**WRONG**
response I get: `{ projects: project[], username: string`
<img width="476" alt="Screenshot 2023-03-08 at 14 28 55" src="https://user-images.githubusercontent.com/94218081/223725536-27e9c625-6400-4b18-b91c-0bd066cb6143.png">

**RIGHT**
response I need: `{ data: project[], metadata: { total: number } }`

**Comment by YukihiroSM** [comment]
@ruslankotliar 
<img width="1701" alt="CleanShot 2023-03-18 at 10 47 47@2x" src="https://user-images.githubusercontent.com/37514514/226095399-7d4d8af4-3f2c-449b-ad18-f51d694772b5.png">
Looks like it works now. At least, locally))
Is the project response structure correct?

**Comment by YukihiroSM** [comment]
Now it works as expected
<img width="1691" alt="CleanShot 2023-03-18 at 10 52 25@2x" src="https://user-images.githubusercontent.com/37514514/226095597-5157f70b-6ccb-44a4-99fd-a966c5f430f5.png">
